libretro/graph.c
libretro/graph.h
libretro/libretro-glue.h
libretro/libretro-mapper.c
libretro/libretro-mapper.h
libretro/libretro.c
sources/src/osdep/retroglue.c
sources/src/osdep/retroglue.h

Fixes mainly on the resolution selection process.
The file libretro-mapper.h was missing on the previous commit.

Some fixes and cleanup.

---

Makefile.common
README.md
libretro/libretro.c
libretro/retro_disk_control.c
libretro/retro_disk_control.h
sources/src/archivers/lha/header.c
sources/src/filesys_linux.c

This core now support the usage of M3U file and disk control from within RetroArch for multi disk games.
Documentation was updated.
Build on Linux was also fixed.

Added M3U and Disk control support

---

Makefile
README.md
libretro/libretro.c

Fixes https://github.com/libretro/libretro-uae/issues/16
Fixes https://github.com/libretro/libretro-uae/issues/39
Fixes https://github.com/libretro/libretro-uae/issues/44

Standard amiga resolution & git version display

---

libretro/libretro.c

Adds missing input descriptor for joypad B button

---

libretro/libretro.c

Removed unnecessary options and added a necessary option.
Sound options will come to effect immediately, and not just change the config for the future.

Core options for sound

---

README.md
libretro/libretro-mapper.c
libretro/libretro.c

Just need to append "(MD)" to the filename. Also updated README.
Sorry for the weird indentations, it didn't look like that here.
Closes #38 
Also as a bonus a circumvention regarding simultaneous joystick movements.
Closes #9

M3U handling to support multiple drives

---

README
README.md
libretro/libretro-mapper.c
libretro/libretro.c
libretro/vkbd.c
retrodep/retroglue.c

And a transparency toggle of some kind for the vkbd as a bonus.
Also removed the joy/mouse-toggle from GUI and made it automatic.

Button layout according to Retro Standards

---

libretro/libretro.c

One missing compatibility option added and the rest got some lipstick.
Oops, missed a tiny spot, hence the force.

Core option update

---

README.md
libretro/libretro.c

Sorry for the hassle.
Closes #98

Restore A600 Kickstart 3.1

---

libretro/libretro-mapper.c
libretro/libretro.c

More control additions

---

libretro/diskutils.c
libretro/libretro-glue.h
libretro/libretro-mapper.c
libretro/libretro.c
libretro/vkbd.c
sources/src/cfgfile.c
sources/src/statusline.c

Renovations and fixes

---

Makefile

Fixed the config for the Playstation Classic
Removed lines from makefile as requested by libretro maintainers

PSClassic makefile fixes

---

libretro/libretro-mapper.c
libretro/libretro.c
retrodep/retroglue.c
sources/src/drawing.c

Tried to make as many core options to work realtime as possible.
Also changed core option placements and fixed indentations.
Closes #117

More core options to apply in realtime + crop overscan fix

---

sources/src/custom.c

Finally fastforward works like it should!

Random fastforwarding limit eliminated

---

libretro/libretro-mapper.c
libretro/libretro.c
retrodep/retroglue.c
sources/src/custom.c

Actually this issue in closing was fixed in an earlier PR, but it also relates a little.
And a hotkey for zoom modes as the obligatory bonus.
Closes #120 
Fixes, fixes everywhere: https://youtu.be/xhy7dXWjpAA

Statusbar position fix + fastforward fix + fps counter fix

---

libretro/libretro.c

Useless "real" vs "max" is now "-90%" to "+200%". Makes a rather dramatic difference in Indianapolis 500, for example. Maximum can be increased more if +200% is not enough.
Also reordered some related core options and made cpu options come to effect without restarting.
The bonus is a ninja option `waiting_blits` included in the opposite of `immediate_blits` since they cancel each other out. Fixes graphics corruption in Nebulus 2 on A1200, for example. No ill effects found yet at "automatic".

Replaced "cpu speed" with "cpu throttle"

---

libretro/libretro.c

Combined cpu compatibility core option

---

libretro/libretro-mapper.c
libretro/libretro.c

RA input driver needs to be set to raw in Windows and udev in Linux, afaik. Mouse index needs to be set correctly in RA input configs. Only tested with Windows.
Also added middle mouse button as a bonus.

Support for multiple physical mice

---

libretro/libretro-mapper.c
libretro/libretro.c

Seems to work pretty well maximizing the used screen. Limits itself to current "maximum" setting.

Automatic zoom

---

libretro/libretro.c

- Triggers geometry update also when last_drawn_line changes
-- Fixes autozoom in Bubba n Stix, for example

Autocenter improvement

---

libretro/libretro-glue.h
libretro/libretro-mapper.c
libretro/libretro.c
libretro/vkbd.c
libretro/vkbd.h
libretro/vkbd_def.h

Some minor maintenance and cleanups.
- VKBD had a few buttons labeled wrong according to US keymap
- The keyboard size now stays pretty much the same with both PAL and NTSC when toggled without changing timing
- Removed distracting key borders in the poor man's "transparency" mode

VKBD corrections and tidyings

---

README.md
libretro/libretro-glue.h
libretro/libretro.c
libretro/vkbd.c

- VKBD stays always inside the visible screen regardless of zoomed height & PAL/NTSC & LORES/HIRES
- VKBD controls to README
- Typo fix

VKBD position in zoomed modes

---

libretro/libretro.c

Fixed bad ifelse causing too much zoom in lores guru meditations

---

libretro/libretro.c

Keeps Big Time Sensuality demo loading screen and the likes centered better when zoomed.

Minor adjustment to zoom centering

---

libretro/libretro-mapper.c
libretro/libretro.c

- Altered zoom mode centering value limits
- Added the rest of the RetroPad buttons to keyboard pass-through option
- Added core option for showing/hiding mapping options

Basic maintenance

---

libretro/libretro-mapper.c
libretro/libretro-mapper.h
libretro/libretro.c

Reduces input lag by 1 frame.
---------
Basically, the frontend was constantly running 1 frame behind the emulator. This fixes it.

Upload the current frame instead of the previous one to the frontend

---

COPYING

This was somehow lost in import. Adding back from uae source code

Add back the license

---

libretro/libretro.c
retrodep/retroglue.c

The last Android fix was half baked and had other problems as well. Brainstorm credits to @jdgleaver

Android unzippings yet again

---

libretro/libretro.c
retrodep/retroglue.c

Closes #278 
Also bonus fixed Browse Archive on Load Content.

M3U ZIP fix

---

jni/Android.mk

Whoops, I goofed Android with the tidying, sorry!

Fix Android build

---

README.md
libretro/libretro-core.c
libretro/libretro-glue.h
libretro/libretro-mapper.c
libretro/vkbd.c
retrodep/retroglue.c
sources/src/statusline.c

Major:
- Zoom mode can also do horizontal cropping
- Horizontal + vertical enabled by default
- Please confirm that VKBD touch is bueno with all sizes!
- Remapping adjustments
- Special hotkeys can override VKBD functions
Bonus:
- Prefixes for hidden core options added
- Improved M3U generation sorting
- Waiting blits disabled by default
- Markdown oopsies in README fixed

Zoom mode rework, Remapping fixes

---

libretro/libretro-core.c
libretro/libretro-mapper.c
sources/src/statusline.c

- Statusline LED pixel fixes
- Model preset override simplifications
- Mapper cleanups

Statusline + model preset + mapper maintenance

---

libretro/libretro-core.c
libretro/libretro-mapper.c
sources/src/drawing.c

- LED interface blinking on media access
- Minor cleanups

LED interface, Cleanups

---

README.md
libretro/graph.c
libretro/libretro-core.c
libretro/libretro-core.h
libretro/libretro-glue.h
libretro/libretro-mapper.c
libretro/retro_disk_control.c
libretro/retro_disk_control.h
libretro/vkbd.c
retrodep/retroglue.c
sources/src/caps/caps.c
sources/src/custom.c
sources/src/disk.c
sources/src/drawing.c
sources/src/driveclick.c
sources/src/savestate.c
sources/src/statusline.c

- Core option label tunings
- Disk Control cleanup
- Renamed "libretro-glue.h" to "libretro-core.h"
- Allow using VKBD with arrow keys even when in Game Focus

Misc maintenance

---

libretro/libretro-dc.c

Tabs and 4 spaces to 3 spaces + potential crash fix.

DC cleanup

---

libretro/libretro-glue.c
retrodep/sounddep/sound.c
sources/src/blkdev_cdimage.c
sources/src/include/memory_uae.h

memory.h to memory_uae.h

---

libretro/libretro-core.c
sources/src/drawing.c

Separated one single LED to:
- Power
- Floppies
- HD/CD/MD

LED interface improvements

---

libretro/libretro-core.c
libretro/libretro-glue.c
sources/src/main.c

Fix static build restart, Cleanups

---

sources/src/akiko.c
sources/src/blkdev_cdimage.c
sources/src/filesys.c

Better fix for muted CDA and a fix for paused CDA on state restore.
Bonus temporary filesys logging for Switch.

Savestate+CDA fix

---

libretro/libretro-core.c
libretro/libretro-glue.c
libretro/libretro-glue.h
retrodep/fsdb_host.c
sources/src/fsdb_unix.c

- Reorder WHDLoad config writes
- Prevent write operations with WHDLoad.prefs if the file is not changed
- Fix filesys illegal chars regarding directory creation

WHDLoad + filesys changes

---

libretro/libretro-core.c
libretro/libretro-vkbd.c

Let's make the new fancy text outline optional due to performance concerns.

Optional VKBD text outline

---

Makefile
Makefile.common
README.md
libretro/libretro-core.c
libretro/libretro-glue.c
retrodep/sysconfig.h
sources/src/blkdev.c
sources/src/filesys.c
sources/src/include/isofs.h
sources/src/include/isofs_api.h
sources/src/isofs.c
sources/src/scsiemul.c
sources/src/statusline.c

- Enabled & synced & fixed non-bootable external SCSI CD drives
- Requires "Global Boot HD" enabled and Workbench installed
- Default HD model changed to A1200

SCSI CD drive support

---

libretro/libretro-core.c
libretro/libretro-mapper.c
libretro/libretro-vkbd.c

VKBD color adjustments, Physical mouse option rework

---

libretro/libretro-core.c
libretro/libretro-core.h
libretro/libretro-glue.c
libretro/libretro-graph.c
libretro/libretro-mapper.c
libretro/libretro-vkbd.c
retrodep/sounddep/sound.h

VKBD:
- Color adjustments
- Waits for all inputs to be released before accepting inputs
Other:
- Mouse emulation adjustments
- Dpad mouse acceleration fixed
- Audio cleanups

VKBD + input updates

---

Makefile
sources/src/akiko.c

This should allow building on 32bit Haiku

Fix Haiku 32bit build

---

libretro/libretro-core.c

Exposes the chip RAM as system RAM for cheats and achievements.

Expose chip RAM

---

libretro-common/audio/audio_mixer.c
libretro-common/file/archive_file_7z.c
libretro-common/file/nbio/nbio_stdio.c
libretro-common/include/defines/ps3_defines.h
libretro-common/include/libretro.h
libretro-common/include/lists/nested_list.h
libretro-common/include/net/net_compat.h
libretro-common/include/net/net_http.h
libretro-common/include/net/net_natt.h
libretro-common/lists/nested_list.c
libretro-common/net/net_compat.c
libretro-common/net/net_http.c
libretro-common/net/net_natt.c
libretro-common/net/net_socket.c
libretro-common/rthreads/rthreads.c
libretro-common/samples/core_options/README.md
libretro-common/samples/core_options/example_categories/libretro_core_options.h
libretro-common/samples/core_options/example_categories/libretro_core_options_intl.h
libretro-common/vfs/vfs_implementation.c
libretro-common/vfs/vfs_implementation_uwp.cpp
libretro/libretro-core.c

Core options V2

---

README.md
libretro/libretro-core.c

- Better audio detection in AutoLoadFF
- Readme md5 correction

AutoLoadFF improvements

---

libretro-common/include/streams/file_stream.h
libretro-common/streams/file_stream.c
libretro-common/streams/file_stream_transforms.c
sources/src/filesys.c
sources/src/fsdb_unix.c

Filesys fixup

---

libretro/libretro-core.c
libretro/libretro-glue.c
sources/src/custom.c

More memory options to choose from, plus a correction to a modeline triggering hack.

Expose Z3 Fast RAM + 1.5M Chip

---

README.md
libretro/libretro-core.c
libretro/libretro-glue.c
libretro/libretro-graph.c
libretro/libretro-graph.h
libretro/libretro-vkbd.c
libretro/libretro-vkbd.h
sources/src/drawing.c

VKBD:
- Blended font shadows
- Dimmed surroundings
- Section gap
+ Readme corrections

VKBD enhancements

---

libretro/libretro-core.c
libretro/libretro-core.h
sources/src/driveclick.c

- Core option for selecting cartridge images from system data dir
Closes #538
- Autocrop corrections
- Cycle-exact force correction, which goofed and forced CE when core was started with CE core option

Dynamic cartridge core option

---

libretro/libretro-core.c
libretro/libretro-dc.c

'retro_set_paths' cleanup

---

sources/src/akiko.c

Akiko CD speed hack fix

---

Makefile.common
libretro/libretro-core.c
libretro/libretro-core.h
libretro/libretro-dc.c
libretro/libretro-glue.c
libretro/libretro-glue.h
retrodep/fsdb_host.c
sources/src/cfgfile.c
sources/src/fsdb_unix.c
sources/src/include/fsdb.h
sources/src/include/misc.h
sources/src/misc.c

Non-ASCII path corrections

---

libretro/libretro-core.c

Environment path + option fix

---

libretro/libretro-core.c
libretro/libretro-mapper.c
libretro/libretro-vkbd.c

VKBD cleanups

---

sources/src/fsdb_unix.c

FSDB host illegal char bonus

---

libretro/libretro-core.c

Add option to start with statusbar visible

---

.gitignore
Makefile
retrodep/fsdb_host.c
retrodep/sysconfig.h
sources/src/gen.c
sources/src/include/sysdeps.h

- Makefile additions for easily generating all the generated code
- Build fix for Linux when VFS is disabled
Hopefully helps with #586

FSDB / VFS cleanup

---

libretro/libretro-mapper.c

Aspect variable type fix

---

libretro/libretro-mapper.c

Backport of mouse pointer precision improvement to 2.6.1 (see also https://github.com/libretro/libretro-uae/pull/647)

Increase analog stick mouse precision to sub-pixel

---

libretro/libretro-core.c
libretro/libretro-core.h
libretro/libretro-glue.c
libretro/libretro-mapper.c
libretro/libretro-vkbd.c
sources/src/statusline.c

- Add all extra display modes
Closes #683
- Tighten statusbar spacing to fit everything in narrowest mode
Closes #696
- Fix invalid input bitmask value causing sticky right mouse button in mouse mode with default face button
Closes #698

Fix productivity modes

---

README.md
libretro/libretro-core.c
libretro/libretro-core.h

Add Kickstart 1.1 override option
