- Makefile
- README
- libretro/libretro-mapper.c
- libretro/libretro.c
- sources/src/audio.c
- sources/src/gui-retro/sdlgui.h
- sources/src/hardfile_unix.c
- sources/src/sounddep/sound.c
List of fixes and new features:
- Fix android-armv7 build
- Set core to correct screen timing
- Enable perfect scrolling when running in 50Hz mode (the native Amiga refresh rate)
- Fix sound stuttering and enable 44100 hz samples
- Add "None" led option under core options
- Add config file options "gfx_width" and "gfx_height" which makes it possible for .uae config files to define the native screen resolution to use when launching
- Fix handling of compressed hdf files (hdz files)
> Fix Android build, various fixes and added new features

- sources/src/archivers/lha/header.c
- sources/src/filesys_linux.c
<sys/timeb.h> has been deprecated since POSIX.1-2008 and since Android API 18.
This should fix build problems with the buildbot system.
> Remove deprecated <sys/timeb.h>

- gui-retro/zip.c
$ ldd -r puae_libretro
undefined symbol: MSA_UnCompress        (./puae_libretro.so)
ZIP_ReadDisk is not used and MSA detection is anyways commented out in line 351.
> Fix undefined symbol in debug build

- jni/Application.mk
- libco/aarch64.c
- libco/armeabi.c
- libco/libco.c
I'm not certain how this ever worked on arm, but I'm guessing the older compilers were more lenient on the asm macro. But something in this core, clang *really* doesn't like. Not sure what, and don't have time to research it, so just forcing it to use gcc even when the default changes.
> Updates for android

- Makefile.common
- README.md
- configuration.txt
- libretro/libretro.c
- libretro/retro_files.c
- libretro/retro_files.h
- libretro/retro_strings.c
- libretro/retro_strings.h
You can pass a disk or hdd image (WHDLoad) as a rom.
Supported format are :
adf, dms, fdi, ipf, zip files for disk images.
hdf, hdz for hdd images.
When passing a disk or hdd image as parameter the core will generate a temporary uae configuration file in RetroArch saves directory and use it to automatically launch the game.
Documentation was updated.
> Disk and HDD images (WHDLoad) support

- Makefile.common
This compiles and links in the internal capsimg code. By default this tries to dlopen libcapsimage.so.2. Tested working with Frode Solheim's capsimg fork. I don't think there's any license issue as the capsimage code itself is external.
> Add IPF support through capsimg

- libretro/libretro-keymap.h
The ScrollLock key was mapped to inhibit screen function of puae.
Removed the mapping to allow Game Focus function of retroarch to properly work.
Fix #63
> Fix : Conflict with Game Focus function

- Makefile.common
- README.md
- sources/src/caps/caps.c
- sources/src/caps/uae_dlopen.c
- sources/src/caps/uae_dlopen.h
- sources/src/include/uae_api.h
- sources/src/include/uae_attributes.h
@escalade activated support in #61 but the code was only for linux so windows build was broken.
Ported some functions from https://github.com/FrodeSolheim/fs-uae to make this work on windows too.
Added documentation of IPF support in README.md
Fix #61 
Fix #43
> IPF support through CAPSIMG

- libretro/libretro-keymap.h
- libretro/libretro-mapper.c
- libretro/libretro.c
- retrodep/retroglue.c
Restart does reset now.
Who needs a hotkey for sound muting, really? Anyway frontend should handle that, not the core. The button was active even when it was not set in Controls menu.
Keyboard layout was all over the place, but not anymore.
Shift on the keyboard was forced to be held down on a press, but now capslock does that.
Fixes #69 #51
> Bunch of adjustments

- Makefile
Nintendo targets have only been tested as far as compile, they have not been tested on target hardware.
> Fix mingw cross compile and add some missing nintendo targets

- README.md
- libretro/libretro.c
Added barebone classic A500 and A500+ to the model list.
Changed A600 Kickstart to an authentic one.
Updated README accordingly.
Frameskip option as a bonus.
Closes #89
> More memory settings and finetuning

- libretro/libretro-mapper.c
- libretro/libretro.c
- libretro/vkbd.c
- sources/src/cfgfile.c
Now I promise this is the last one for today, heh.
Reason for the floppy fix was that I launched Push Over and noticed it always clicks the extra drive during gameplay for absolutely no reason, as it does not even use it for the second disk. Sure I could disable the sound emulation completely, but..
> Minor changes

- README.md
- libretro/libretro.c
- sources/src/cfgfile.c
This extra model allows Second Samurai AGA to work.
Also changed the pecking order of the filename detection to check A1200 models first, then A600 and then A500 models.
And since the UAE built in model prefs are never used with this core, I defaulted bogomem to 0. Otherwise A1200 would have bogomem, and that is no bueno.
> Forced bogomem_size to 0 by default, added A1200 model without extra memory, updated README accordingly

- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro-mapper.h
- libretro/libretro.c
- sources/src/custom.c
Attempt at doing resolution and timing switching on the fly. It can be tested for example at Early Startup (hold LMB+RMB while booting A1200). Protracker also has a toggler.
If there is a way to achieve the same result without the desktop flashing, I'm all ears. I could not get the new timing to apply without using RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO, and that causes the flash. Geometry alone updates nicely without the flash.
If nothing else helps then maybe a core option should be added to disable the Hz change but allow the geometry change.
This will fix the double statusbar issue with Dyna Blaster (if the statusbar is at the bottom), but because it uses a weird 60Hz PAL mode (but acts like normal NTSC on a real Amiga), and it keeps returning to PAL for a split second during loadings …
> Dynamic PAL/NTSC switching

- README.md
- libretro/libretro.c
- sources/src/custom.c
- sources/src/include/custom.h
- sources/src/savestate.c
Took some code from a more up-to-date WinUAE to stabilize interlaced mode.
- Wizkid does not strobe anymore
- CELTIC-MultiscrollerScroller stays at 50fps
Added "(PAL)" and "(NTSC)" detection to filename as a bonus.
Closes #114
> Fix flashing interlacing

- libretro/libretro.c
- sources/src/cfgfile.c
It uses a temp file like the VICE core, but the state restoring needs to be requested to be fired at the right time in m68k_go().
Only drawback for now seems to be rewinding, which is unusably slow. Still better than nothing.
Closes #109
> Savestate support

- libretro/libretro-mapper.c
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/inputdevice.c
Had to bring some dynamite, because there was something wrong with the controls. Now it feels pretty much perfect. Please prove me wrong.
Changed the keyboard handling so the underlying keyboard key isn't pressed if using keyboard as RetroPad. For example in Turrican II the CTRL key pauses, and if CTRL key was the fire button, you're out of luck. And in Banshee the CTRL key also does the flip, so CTRL key as fire was no bueno. It can be overriden with the same Right Alt which overrides cursor keys without changing device type to keyboard.
Also changed the behavior of the D-Pad mouse speed toggler. Now it acts as a modifier which goes either faster or slower depending on the new core option starting point.
And again a little less compilation warnings.
And the bonus: Included joyport …
> Controller related updates

- README
- README.md
- libretro/libretro-mapper.c
- libretro/libretro.c
Prevented 2nd fire button from firing if RetroPad A is mapped to a key.
Made a minimal correction to uncropped NTSC geometry. Normally it is set at 480/240px, and that is where statusbar will be drawn, but UAE does not output NTSC quite that far, making the statusbar not clearing properly.
Also updated and corrected readme again (removed dead links and made reading easier).
> Assortment of minor goodies

- libretro/libretro-mapper.c
Fixed the duplicate button skip to affect only RetroPad and made Keyrah keys also act properly with the same axis shenanigans.
> Proper dupefire location + Keyrah handling correction

- libretro/libretro-mapper.c
- libretro/libretro.c
- Made zoom autocentering more reliable
- Removed the need for an ugly hack caused by PAL/NTSC difference in minfirstline
- Took influence from the Dosbox core for analog stick mouse control and tried to make it non-linear
Surprisingly even Cannon Fodder is pretty playable now with the stick.
> Improved zoom autocenter + analog stick mouse

- libretro/libretro-mapper.c
- sources/src/cfgfile.c
- Pressing Enter works as a selector in the VKBD, mainly for the keyboard device type
- Enabled serial.device, otherwise Skidmarks start menu would lock up and nothing works
Closes #137
> Minor usability and major compatibility fix

- libretro/libretro-mapper.c
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/inputdevice.c
Note that this does not enable the use of 2 physical mice, but only RetroPad emulated.
And since the mouse and joystick ports are reversed in Amiga, as in the first mouse port is the second joystick, and the second mouse is the first joystick, this simply works just like RetroPad works now: Both ports can control the other port as mouse directly via analog sticks in joystick mode, and mouse mode forces D-Pad and the first 2 buttons to mouse.
Hotkey mouse buttons and mouse speed modifiers apply to the controller in question.
There is very little leg room to make this any simpler and clear-cut without creating another device type, which would skip joystick control completely. I don't think that is necessary.
Bonus: A global mouse speed core option which affects all mouse types
Closes #140
> Mouse support for both normal joyports

- libretro/libretro-mapper.c
- Fixed joystick port from going into mouse mode without moving it as a mouse
-- Caused left/right to stay down the first time they are pressed (but not up/down)
-- Came about in the multiple mouse update
--- This will also happen with the mouse port if used as a joystick, and it can't be prevented without changing the default mode to joystick, but that would make mouse to not work unless mouse button is pressed, so I think we can live with it
--- It could be fixed though with a dirty hack of just pressing left and right twice silently at startup, and it would not affect regular mouse usage
- Fixed broken Keyrah handling caused by a typo
- Cleaned up key processing functions
Closes #150
> Controller fixes

- libretro/libretro.c
- sources/src/drawing.c
- sources/src/inputdevice.c
- Vertical offset manipulation changed from minfirstline to thisframe_y_adjust
-- Fixes drawn line calculations = more reliable autozooms and autocenterings
-- Also fixes interlaced modes statusbar position shifting, like Wizkid
- Changed 2nd fire pull-up resistor behavior, fixing 2nd fire working only once on certain games, like Banshee
As always, testing and reports are more than welcome!
> Vertical positioning + Autozoom + 2nd fire improvements

- libretro/libretro.c
Better workaround for the constantly running timer (which makes sure screen is centered and zoomed correctly), because there is no reason for it anymore, other than when a savestate is loaded.
> Autocenter optimization

- libretro/libretro.c
Just a small fix for one missing line. Noticeable in Cannon Fodder intro logo screen (missing the white line at the bottom) and gameplay (missing last line from the map globe), for example.
> Autozoom calculation correction

- sources/src/filesys_linux.c
- sources/src/fsdb_unix.c
- sources/src/fsusage.c
Reading and writing with WHDLoads seems to be finally ok now. Only confirmed on Windows, so let's not update Readme just yet.
- Used/available size faked like in FS-UAE
- Protect flags on all files are +e, so executing works without Workbench and/or explicit flagging
- "." and ".." are for some reason seen as files and not directories, so enabled hiding them too
> Directory filesystem fixes

- libretro/libretro-mapper.c
- libretro/libretro.c
Basic maintenance:
- Capitalized all core options
- All sublabels end with a "."
- Reordered core options
- Options go smaller to bigger from left to right
Bonus statusbar changes:
- Changed joystick/mouse mode indicator to dynamic port indicators (Joystick, Mouse, Keyrah)
- Extra parallel adapter joyport labels visible only when plugged in Controls menu
> Core option labels according to RetroStandards

- libretro/libretro-mapper.c
- libretro/libretro.c
- sources/src/drawing.c
- Statusbar simplified to fit in one row in lores mode
- Zoom mode hotkey toggles the mode on/off and not jump to the next one
- Horizontal position core option with automatic centering
-- Does not throw Banshee off screen, and does keep Turrican centered, but for some reason makes North & South less centered..
Closes #164
> Miscellaneous bunch

- README.md
- libretro/libretro.c
- libretro/vkbd.c
- Hires core option changed to "Video Resolution" with 3 modes: Lores, Hires single, Hires double
- Raised PAL resolution height to 574
- Fixed lores mode black screen introduced with horizontal position option calculation
Closes #173
> Single line high resolution mode

- libretro/libretro-mapper.c
- libretro/libretro.c
- libretro/vkbd.c
- sources/src/ar.c
- sources/src/cfgfile.c
- sources/src/main.c
- sources/src/memory.c
- sources/src/statusline.c
- Zoom toggling fixed to obey core option better
- No more crashing when ejecting a non-existing disk, thanks to an unwarranted strlen
- Statusline made shorter by replacing last floppy LED with hard disk LED when HD enabled
- Removed statusline floppy indicator track numbers when ejected and also HD text
- More readable and useful logging at startup and at runtime
> Minor faults eliminated

- Makefile.common
- README.md
- libretro/libretro.c
- DMS support was not working at all despite being on the valid extension list
- Internal ZIP support is not working (and did not succeed in it), and a ZIP will never go that far in the first place, because RA does the unzipping, so changed it to ADZ (gzipped ADF) which does work
Also is there a real reason to keep the FDI format? I tried to search for a disk for testing but couldn't find one in a reasonable time.
> File support changes

- README.md
- libretro/libretro-mapper.c
- libretro/libretro.c
Since the default A500 is not HD bootable, the new default automatic mode makes juggling between floppies and hard drives more convenient. It selects A500 with floppies and A600 with hard drives, if there is no filename override tags.
Also made the new automatic sound filter type the default, because of course it should match the used model.
Removed the need for ()-chars with OCS, ECS & AGA tags, because AGA games tend to already have AGA in the title, so no need to make it `AGA (AGA)` or change it to `(AGA)`.
Altered A500+ model to be more realistic with only chip ram.
And the bonus is yet another tinkering with the keyboard pass-through.
> Automatic default modes for core options: model & filter type 

- Makefile
- [Buildbot](http://paste.libretro.com/176027) is using `platform=unix-armv7-hardfloat-neon` for linux-arm7neonhf build
- So now it matches platform which contains `unix` not strictly `unix`
> Fix linux-arm7neonhf build

- README.md
- libretro/graph.c
- libretro/graph.h
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro-mapper.h
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/include/drawing.h
New features:
- Video resolution core option no longer requires core restart, but only a soft reboot
- PAL resolution changed to full 576p/288p
- A minor last line drawing thing preventing the use before is now dealt with
Issues solved:
- Many interlaced screens got zoom calculations off the rails and so zoom shaked horribly, like CD32 boot screen and Turrican Anthology Compilaton start menu
- Fire & Ice CD32 not triggering zoom correctly and not centered horizontally
- Crashing with 24-bit hires double line mode
Bonus:
- Combined CD32 KS + extended ROM file support option with the same name
- CD32 extended ROM only searched if KS ROM size is 512KB, combined will be 1MB
- Cleanups
> Video maintenance

- README.md
- libretro/libretro.c
- libretro/retro_disk_control.c
- libretro/retro_disk_control.h
This PR adds the ability to automatically generate one or more blank save disks when creating an M3U playlist.
- On any line of the M3U file, the following my be entered: `#SAVEDISK:VolumeName`
- `VolumeName` is the disk label - this is optional, and may be omitted to create an unlabelled disk image (only certain games require save disks to have specific labels)
- Save disks are created in the user's save directory, with the following name: `[M3U_FILE_NAME].save[DISK_INDEX].adf`
@sonninnos I realise you are the maestro when it comes to this core - please let me know if you object to anything I've done here!
> Add support for auto-generated save disks in M3U playlists

- libretro/libretro.c
While updating RetroArch's disk control interface code (https://github.com/libretro/RetroArch/pull/10045) I noticed that the `disk_replace_image_index()` function of this core breaks spec by always returning `false` - this will make 'append disk image' operations fail.
This trivial PR just makes `disk_replace_image_index()` return `true` when successful.
> Fix disk_replace_image_index() return value

- libretro/libretro.c
- sources/src/akiko.c
- sources/src/blkdev.c
- sources/src/blkdev_cdimage.c
- sources/src/cdtv.c
- sources/src/include/akiko.h
- sources/src/include/savestate.h
- sources/src/main.c
- sources/src/newcpu.c
- sources/src/savestate.c
- sources/src/statusline.c
- Quick Menu Restart recreates UAE conf and really restarts instead of Ctrl-Amiga-Amiga (which can be done via VKBD/hotkey)
- Added Core option for CD32 NVRAM shared / per game, default is disabled = per game
- Fixed CD eject & insert & append
- Fixed CD audio not playing properly after loading a savestate that was saved while CD was playing
- Finetuned statusbar LED colors
+ Some CDA related backports:
- https://github.com/tonioni/WinUAE/commit/39f941629f141e763d8f51f2638ccf9c9fed368c
- https://github.com/tonioni/WinUAE/commit/7577556405c09d09084925c08dc6331a6b17557c
- https://github.com/tonioni/WinUAE/commit/c4fca99972a6bbe8212d91287dacc0a2d4fd5695
> Content related updates

- libretro/libretro.c
- sources/src/filesys.c
For some reason HDF volname is always null when doing savestates, and some platforms do not like it.
Debugging/brainstorm credits to @realnc 
Also changed default WHDSaves.hdf to disabled to use raw files.
Closes #219
> Band-aid for missing volname&filesysdir

- libretro/libretro-glue.h
Sorry for the hassle, you merged ~30sec too soon, heh.
`68ec020` did not resolve to the correct value using `cpu_model` instead of old fashioned `cpu_type`. I changed it because `cpu_type` would not pick up `68030`.
Please merge ASAP, because otherwise A1200 & CD32 remain broken!
> 68020 fix for 'cpu_model'

- libretro/libretro-mapper.c
- libretro/libretro.c
- retrodep/sysconfig.h
- sources/src/disk.c
- sources/src/filesys.c
- sources/src/filesys_linux.c
- sources/src/fsdb.c
- sources/src/fsusage.c
- sources/src/include/filesys.h
- sources/src/include/fsdb.h
- sources/src/include/fsusage.h
- sources/src/include/parallel.h
- sources/src/include/zarchive.h
- sources/src/include/zfile.h
- sources/src/serial.c
- sources/src/zfile.c
- Archive & directory access up to par
= Some non-working LHAs can be taken off the list, such as:
- BeneathASteelSky_v2.1_CD32
- DeluxeStripPoker2&DataDisks_v1.0
Should also deal with #241
> Filesystem fixes

- README.md
- libretro/graph.c
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/custom.c
- sources/src/newcpu.c
- Added more useful information (resolution, memory, model) to the statusbar
Closes #235 
- Fixed double line deinterlacing
So instead of this:
We get this:
And instead of this unreadable mess:
We get this:
(Yes the before-screenshots are Single Line, but currently Double Line does the same bob deinterlacing, so didn't bother to remove the fix and compile again just for the screenshot)
And of course the complimentary WB shot:
Same as a raw RA screenshot with aspect ratio correction:
- Separated Resolution and Line Mode core options
- New default Video Resolution: Automatic
- Defaults to Hires and switches to SuperHires when resolution is sensed
- Only WB tells the resolution cleanly, so had to resort to hackery to get Super Skidmarks to register
- New default Video Line Mode: Automatic
- …
> Visual upgrades & CPU adjustments

- libretro/libretro-glue.h
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/disk.c
- sources/src/drawing.c
- sources/src/include/savestate.h
- sources/src/include/uae.h
- sources/src/inputdevice.c
- sources/src/inputrecord.c
- sources/src/newcpu.c
- sources/src/savestate.c
At present, the core implements save states using a temporary state file generated by the core itself. This is quite slow, but more importantly it causes a huge amount of unnecessary disk writes - when saving/loading the state of a WHDLoad install, for example, it is very easy to rack up many hundreds of megabytes of written data (not good for flash storage!). Writing to disk like this also precludes frontend features like rewind, readahead, etc.
This PR implements purely memory-based save states, so no more unnecessary disk writes.
**Note 1:** Rewind is quite useable now, provided granularity is set moderately high - 5 frames or so. *However:* rewind does not work reliably/at all for WHDLoad installs (and it can also fail when using an `(MD)` floppy disk playlist)
**Note 2:** Runahead …
> Use memory-based save states

- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro.c
- sources/src/custom.c
This is a follow up to PR #249. It includes the following fixes:
- At present, any call to `retro_update_av_info()` that occurs outside of `retro_run()` is ignored (since it is unsafe to invoke this anywhere else). Such calls may happen on the first frame, and when loading a save state - and it turns out that this can cause problems in certain edge cases. For example, when running some NTSC content, we end up with the wrong video dimensions (until the next resolution change). This sort of error was hard to detect! Many apologies for missing it. This PR fixes the issue by deferring any av info updates that occur outside the main runloop to the next call of `retro_run()`.
- It turns out that rewind functionality can break in certain games due to an increase in save state size during …
> Save state fixes

- README.md
- libretro/libretro-glue.h
- libretro/libretro.c
- retrodep/retroglue.c
Blocked the frontend extraction and added some simple logic to determine the content:
- M3U playlist will be created and launched when floppy disks are found
- Hard drive and CD images take precedence and the first one is picked when found
- Perhaps later combine floppies and hard drive images to work together..?
- If no images are found, the content will be seen as a directory, thus also making zipped WHDLoad installs usable
Please point out if I missed any use case! Any potential problems with the way of clearing out the temp files at deinit?
> Extended ZIP support

- libretro/libretro.c
- retrodep/retroglue.c
- retrodep/retroglue.h
- sources/src/fsdb_unix.c
- sources/src/statusline.c
- Core option for having a HD always attached, with HDF creation, as requested in #246 
- HDF size options in MB are: 20, 40, 128, 256, 512
- Files mode is ready for use without formatting
+ Filesys fixes:
- Files under `S:` are always considered as scripts
- Invalid filenames under WIN32 handled to prevent Workbench install failing in Files mode
+ Fixed RA disk index being at the last disk when `(MD)` is used, even though only the first drive is managed by the disk control
+ Fixed statusbar to show floppies with HD setups only when floppies are inserted
> Global Boot HD core option with HDF creation, Filesys fixes

- libretro/libretro-glue.h
- libretro/libretro.c
- libretro/retro_disk_control.c
- libretro/retro_disk_control.h
- sources/src/disk.c
- sources/src/include/savestate.h
- sources/src/savestate.c
This PR makes two small improvements to save state handling:
- When loading floppy disk content via `m3u` files, restoring a save state now updates the frontend with the correct 'currently selected' disk index (previously this was left at whatever index was selected before restoring the state, which was often wrong and made for a confusing user interface...)
- When creating save states, the memory buffer is now created with the correct 'final' size (instead of relying on dynamic allocation, expanding as required). I didn't actually expect this to have much effect, but it turns out all those `realloc`s were quite expensive: previously I could only run at fullspeed with rewind enabled with a granularity of 4-5 frames - now I can drop this down to 3.
> Minor save state improvements

- Makefile
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro.c
- libretro/vkbd.c
- libretro/vkbd.h
Only tested with Windows and mouse, since `RETRO_DEVICE_POINTER` also reacts with it. Hence also disabled real mouse control while VKBD is visible.
Bonus:
- Switched O2 to O3 for a small performance boost. No ill-effects witnessed yet, but standing by for surprises from other platforms.
> VKBD touch control

- README.md
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro.c
- libretro/retro_disk_control.c
- retrodep/retroglue.c
- retrodep/retroglue.h
- sources/src/statusline.c
More use cases for archives and playlists:
- Floppy images can be zipped in M3Us
- Disk Control insertion understands ZIPs and M3Us
- ZIP with a single disk will append, multiple files and M3Us will replace
- Insertion will also accept UAE/HDF/LHA, which will require core restart
Bonus:
- CDTV (core option + file tag)
- Global conf file `puae_libretro_global.uae` 
- Statusbar adjusting
> M3U+ZIP handling, CDTV option

- libretro/libretro-mapper.c
- libretro/libretro.c
Controls:
- In analog joystick mode D-Pad did nothing, therefore it now always controls mouse to minimize manual joy/mouse switching
- Core option for reordering joystick ports
- Aimed at Arcadia and 4-player adapter games
Automatic zoom:
- Less aggressive operation = the change of geometry now requires first and last drawn lines to stabilize for couple of frames
- Downside is that there is a minor delay in the zoom, but upside is that there are less unwarranted and pointless geometry changes
- Mainly affects games with full screen slide animations and other transition gimmicks that trigger the calculations, mostly for no proper reason
- Clear performance improvements at least in: Sink or Swim, Tiny Skweeks, Pinball Fantasies CD32, Soccer Kid AGA
- Finetuned maximum `thisframe_y_adjust` …
> Controls + Automatic zoom updates

- Makefile
- libretro/libretro.c
- sources/src/driveclick.c
Closes #269 hopefully, please confirm!
Also removed stripping, because the space saved is rather minimal, and the benefit of getting readable results straight from `retroarch_debug.exe` is still more valuable.
Bonus:
- Horizontal centering optimization
- Fixes Test Drive II intro crash when the Porsche is desperately trying to be centered
- Core option for disabling floppy sounds with empty drives
> Fix Android unzip issue, Remove gcc stripping "-s"

- README.md
- libretro/libretro.c
Currently filename tags are having the last word when the model is chosen, and that conflicts with the core option somewhat.
For example when trying to force a CDTV game to CD32 mode via core options if the file is in a directory that matches the tag "CDTV", it can't be done because the filename matching actually searches the whole path.
This PR changes the pecking order to model core option having the final say, so that game-based overrides can be used whatever the case may be. Filename tags are searched only with the "Automatic" model, like Guru intended.
Any possible blindspots? Seems to working fine. Relates to #272 but does not close.
Also some minimal bonus rewordings and rephrasings to Readme, verbose log and option labels.
> Change model force hierarchy, Option label updates

- libretro/libretro.c
- retrodep/sysconfig.h
- sources/src/blkdev.c
- Added a core option for delayed CD insert on startup for those pesky games that won't run when powering on with disc inserted, even on the real thing (Xenon 2 CDTV, Total Carnage CD32)
Closes #272 
- Yet another pointless work reducing autozoom improvement:
- Skip geometry update if the used values return back to the original values during the stabilization period (Lethal Weapon screen fades)
- Fixed sound filter type not updating on startup, which seems to have been broken for a long time, from libco removal perhaps
Bonus:
- Found a way to remove my hacks to get CD eject/insert detection working by adding `#define SCSIEMU`, because only then was `blkdev_vsync()` run, which does the necessary `check_changes()` automatically
> CD startup delayed insert, Autozoom improvement

- README.md
- libretro/libretro.c
- retrodep/retroglue.c
- sources/src/custom.c
- sources/src/drawing.c
- sources/src/include/drawing.h
New stuff:
- Replaced current framerate halving double line frame with full framerate double line field
- Added core option "Remove Interlace Artifacts" which behaves best on static screens
- Confusingly the option is named `gfx_flickerfixer` in confs and `gfx_scandoubler` internally, but according to the changelog it is neither:
> - "Flicker fixer" renamed to "Remove interlace artifacts" (it really
isn't same as flickerfixer or scandoubler)
Fixes:
- Sound filter type option was accidentally forced at "Automatic"
- More autozoom+centering solutions
- Allow UAE internal centerings but prevent RA geometry sets in certain situations
- Random crash when changing resolution and interlacing at the same time in WB
Bonus:
- Core option unifications and reorganizings
> Backport double line field interlace

- libretro/libretro.c
Just a small fix this time. The right answer was right in front of me but I took a wrong turn which didn't even work correctly, sorry about that.
> Fix calling init_custom() for no reason

- libretro/libretro.c
- sources/src/zfile.c
At present, the core will crash the second time content is loaded when using a static build (Switch, etc.). I don't have any supported hardware to test this on, but by building under Linux using the `--enable-preserve_dylib` configure option I was able reproduce a segfault and graphical corruption caused by static variables carrying over incorrect values from the previous run.
This trivial PR 'resets' these static variables appropriately. I hope this will fix issue #215 - if anyone could test a static build, I would be grateful!
> Attempt to fix crash when reloading core on static builds

- README.md
- libretro/libretro-core.c
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
Major:
- Model presets can be customized with config files
Closes #285 
- Region forcing via filename tags is optional, default is enabled
Minor:
- No-Intro tags added to region forcing
- Corrections to real NTSC behavior (aspect ratio toggle, statusbar position)
Bonus:
- Core option for defaulting/setting D-Pad control mode (Joystick/Mouse)
> Model preset overrides, Optional region search

- README.md
For those who legally purchase BIOS from Amiga Forever, here are the appropriate naming conventions.
With the dozens of BIOS that come in the Amiga Forever Plus Edition (minimal purchasable to acquire the necessary BIOS), it can become a little confusing for some knowing what to rename to what.  Tested and Approved with latest Plus Edition!  
The interesting difference is that older Amiga Forever Releases actually required a rom.key, as a security check, in order to utilize the BIOS.  Removal of the rom.key necessitation in more recent Amiga Forever Releases pretty much identically approximates the md5s for both sets, aside from the missing combination KS + extended v3.1 rev 40.060 AKA kick40060.CD32
> Amiga Forever legal BIOS naming conventions

- libretro/libretro-core.c
- sources/src/custom.c
- sources/src/savestate.c
Regular:
- Autozoom improvements
- The earthquake effect in "Lollypop" no longer resizes the geometry
- Please let me know at once if something else is or got broken!
- Content path can include non-ascii characters like `å` `ä` `ö`
Bonus:
- "Wait for Blitter" restored as the default
- Logging noise reduced
> Autozoom improvements, Content path unicode

- sources/src/caps/caps.c
Allow placing capsimg library also in the executable path. Aimed at Android+dlopen permission issue:
> 06-11 15:40:47.611 13410 13429 E linker  : library "/storage/emulated/0/RetroArch/system/capsimg.so"
("/storage/emulated/0/RetroArch/system/capsimg.so") needed or dlopened by
"/data/data/com.retroarch.ra32/cores/puae_libretro_android.so" is not accessible for the namespace: [
name="classloader-namespace", 
ld_library_paths="",
default_library_paths="/data/app/com.retroarch.ra32-1/lib/arm:/data/app/com.retroarch.ra32-1/base.apk!/lib/armeabi-v7a",
permitted_paths="/data:/mnt/expand:/data/data/com.retroarch.ra32"
]
> Fallback for capsimg path

- README.md
- libretro/libretro-core.c
- libretro/libretro-mapper.c
- sources/src/fsdb.c
- sources/src/fsdb_unix.c
Major:
- Updated directory filesystem with illegal filenames
- In practice fixes the Space Taxi 3 input config screen in Windows directory mode, because `con` needs to be named `__uae___con` on the host and vice versa in the emulation
- Allowed launching extracted `.slave` files
- Does not actually launch the correct slave when there are multiple slaves, so for now it just does the same as launching the directory!
Minor:
- Added RetroPad B to turbo fire options
- Defaulted RetroPad X to Space
- Defaulted RetroPad mapping options visibility
> Directory filesystem fix, Control maintenance

- libretro/libretro-core.c
- Widescreen zoom presets adjusted to match VICE core behavior, as in instead of increasing height, it decreases width when things get tight
- Addition to previous `.slave` launching to also accept `.info` (directory and slave)
> Zoom preset adjustments, .info launching

- retrodep/sysconfig.h
- sources/src/fsdb_unix.c
- sources/src/zfile_archive.c
- Removed redundant leftover steps (`tmp_nname` shenanigans) during initial feature inclusion, which caused random crashes in some cases
- Fixed heap block past requested size -errors if Amiga is rebooted after accessing a `__uae___`-prefixed file and the same file is accessed again
- Fixed illegal filesystem character handling for directories
Some WHDLoad slaves such as "Pinball Dreams" and "Hook" will use rather harsh naming conventions for save directories when saves are redirected using `SavePath` (mandatory for readonly-LHA launching):
- `-->PinballDreams<--`
- `->HOOK<-`
Which means these need to be renamed and evaded, and the current maneuvers were only targeting the file named `con` in Space Taxi 3.
If WHDLoad installs are used as extracted files or if the core option is in …
> (Oh No! More) Directory filesystem fixes

- Makefile.common
- README.md
- libretro/graph.c
- libretro/graph.h
- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-keyboard.i
- libretro/libretro-mapper.c
- libretro/retro_disk_control.c
- libretro/retro_disk_control.h
- libretro/retro_files.c
- libretro/retro_files.h
- libretro/retro_strings.c
- libretro/retro_strings.h
- libretro/vkbd.c
- libretro/vkbd_def.h
- retrodep/debug.c
- retrodep/retroglue.c
- retrodep/sounddep/sound.c
- retrodep/sounddep/sound.h
- retrodep/target.h
- retrodep/threaddep/thread.c
- retrodep/threaddep/thread.h
- sources/src/custom.c
- sources/src/drawing.c
- sources/src/inputdevice.c
- sources/src/statusline.c
New:
- Filepath tag `(CE)` for forcing Cycle-exact (core option does nothing)
- Reduced `RETRO_ENVIRONMENT_SET_GEOMETRY` calls with Zoom Mode
Horizontal centering changes:
- Added hacks for:
- North & South (slightly not centered)
- Zool (menu jumps left & right)
- Fixed offset:
- Toki (not centered)
Please report any regressions!
Cleanups:
- Changed `// Comments` to `/* Comments */`
- Reorganized and renamed libretro variables for better readability
- Simplified hotkey mapper
- Removed debugger & internal keymap = core sized reduced ~110kB
- Minor statusbar pixel adjustments
- Separated horizontal + vertical centering functions
> More maintenance

- libretro/libretro-core.c
- libretro/retro_disk_control.c
Added the proper alternative to achieve the same result without renaming files. Disabled by default, but can be kept enabled even if the game does not support external drives, because internal drive disk changing still works as usual.
> Core option for floppy MultiDrive "(MD)" file path tag

- Makefile
- retrodep/memory.c
Ubuntu 20.10 and others have upgraded to GCC 10 and/or Linux 5.5 or newer kernels breaking the build:
- GCC 10.x defaults to -fno-common which breaks the build: add -fcommon to Makefile / CFLAGS to enforce pre GCC 10 behavior ( more info: https://gcc.gnu.org/gcc-10/porting_to.html )
- sysctl system call was removed in Linux 5.5 and Ubuntu 20.10 ships with 5.8 kernel; wrap sysctl in retrodep/memory.c to ifdef __APPLE ( more info https://man7.org/linux/man-pages/man2/sysctl.2.html )
Looks like sysctl(mib, 2, &totalphys64, &len, NULL, 0); syscall is only used inside #ifdef __APPLE__ block in retrodep/memory.c. It feels pretty safe to wrap #include <sys/sysctl.h> to #ifdef __APPLE__ to make this problem disappear. 
sources/src/od-generic/memory.c has similar sysctl construct, but since it …
> Ubuntu 20.10 build fix

- libretro/libretro-core.c
- libretro/libretro-dc.c
- Enable Floppy MultiDrive by default
Closes #338 
- Prevent runahead startup crash
> Floppy MD enabled by default, Runahead startup crash fix

- libretro/libretro-core.c
- libretro/libretro-graph.c
- libretro/libretro-graph.h
- libretro/libretro-mapper.c
- libretro/libretro-vkbd.c
This PR backports the VKDB optimisations from the VICE core: https://github.com/libretro/vice-libretro/pull/315
This reduces the performance overheads of rendering the VKBD by the following amounts (using default settings):
- 16 bit mode: 73%
- 32 bit mode: 78%
> VKBD Optimisations

- Makefile
- retrodep/machdep/support.c
- sources/src/cda_play.c
- sources/src/disk.c
- sources/src/include/a2091.h
- sources/src/include/cda_play.h
- sources/src/include/inputdevice.h
- sources/src/include/newcpu.h
- sources/src/main.c
- sources/src/misc.c
- Header guards for `GIT_VERSION`
Closes #347 
- Removed the need for `-fcommon`
> Gitless build fix, gcc10 cleanups

- libretro/libretro-core.c
- Less build warning oopsies
- WHDLoad WriteDelay adjusted depending on WHDLoad mode
- No delay with files, 50 for HDFs (current default)
> WHDLoad WriteDelay, Cleanups

- libretro/libretro-core.c
- libretro/libretro-dc.c
The way the function was used was doing the job twice in Linux.
> Use 'path_remove_extension()' properly

- libretro/libretro-core.c
- libretro/libretro-dc.c
- libretro/libretro-dc.h
- libretro/libretro-mapper.c
- libretro/libretro-vkbd.c
- libretro/libretro-vkbd.h
- sources/src/cfgfile.c
A new VKBD hotkey under CapsLock+Statusbar (STBR): Save Disk (SVDS)
- First press creates the disk if it does not exist, changes DC index and cycles eject
- Second press changes back to the previous disk
The created disk is automatically appended to DC at next run, but not inserted to external drives. It automatically changes to extended format if the game wants to format a non-DOS disk (Cannon Fodder).
Plus:
- BootHD corrections
- VKBD size stabilizing
> Save disk hotkey, VKBD cleanups

- libretro/libretro-core.c
- retrodep/fsdb_host.c
- Do the rest of WHDLoad files-mode file copying (prefs+key) host-side
- No longer necessary to have RASystem: mounted
- Fopen flag correction (fixed file appending from truncating)
- Hard drive reordering
- Filesys logging adjustments
> WHDLoad Files-mode + filesys fixes

- libretro/libretro-core.c
- Fixed Horizontal Position core option from setting proper custom values at startup
- Added Automatic Zoom width calculation exceptions for 2 problem cases (which report empty area as used area): AfterBurner & Walker
> Horizontal centering corrections

- deps/libchdr/src/chd.c
- libretro/libretro-core.c
- libretro/libretro-glue.c
- libretro/libretro-glue.h
- libretro/libretro-mapper.c
- libretro/libretro-vkbd.c
- retrodep/fsdb_host.c
- retrodep/gui.c
- retrodep/hrtimer.h
- sources/src/akiko.c
- sources/src/archivers/lha/lha.h
- sources/src/blkdev.c
- sources/src/blkdev_cdimage.c
- sources/src/cdtv.c
- sources/src/cia.c
- sources/src/statusline.c
VKBD:
- Better readability with font outline instead of simple shadow
- Reworked core option with new "Automatic" default
CDA:
- Upstream sync and backports
- Changed CDA playback LED behavior from blink to steady
CHD:
- Fixed crash when restoring state with more than average amount of audio tracks
- Fixed CDA track starting frame
Bonus:
- Statusline color adjustments
- Removed deprecated `ftime`
- Comment and unused stuff cleanups
> VKBD improvements, CDA+CHD fixes

- retrodep/fsdb_host.c
- sources/src/disk.c
- Use a different method for getting file size from host filesystem
- Halved the delay of reinserting floppies
> my_fsize rewrite, Shorten floppy insert delay

- Makefile
- README.md
- libretro/libretro-core.c
- libretro/libretro-mapper.c
- Rewordings and corrections to core option label + README
- Add `-Wno-format-security` to Makefile
- Prevent duplicate VKBD press when keyboard Return is RetroPad Start
> Minor corrections

- Makefile
- sources/src/caps/caps.c
For platforms like PS3 where cores are statically linked to RetroArch, CapsImg library have to be linked when final RetroArch SELF is built.
make adding parameter ´capsimg=1´ for example ´make platform=ps3 capsimg=1´
At RetroArch compiling time, add ´-lcapsimg´ as additional library.
------------------------
```
[libretro INFO] Opening cfgfile '/dev_hdd0/game/RETROARCH/USRDIR/savefiles/puae_libretro.uae' 
[libretro INFO] Known ROM 'KS ROM v1.3 (A500,A1000,A2000)' loaded 
[libretro INFO] CAPS: library version 5.1 
[libretro INFO] CAPS: type:1 date:13.6.2003 2:13:47 rel:298 rev:1 
[libretro INFO] Building CPU table for configuration: 68000 24-bit
[libretro INFO] 1883 CPU functions 
[libretro INFO] Building CPU, 44316 opcodes (0 0 1) 
[libretro INFO] CPU=68000, FPU=0, MMU=0, JIT=CPU=0. …
```
> add IPF support to PS3

- libretro/libretro-core.c
- libretro/libretro-glue.c
- libretro/libretro-graph.c
- libretro/libretro-graph.h
- sources/src/cfgfile.c
- sources/src/main.c
- sources/src/misc.c
- Remove temporary config write
- Feeds the uae conf directly without exporting `puae_libretro.uae`, but the old file stays until manually deleted
- Set achievements support
- Always check for missing WHDLoad Kickstarts in files-mode
- libretro graph update
- Fixed debug build by removing some INLINEs
> Remove temporary config write

- libretro/libretro-core.c
Due to some platforms not handling such a bit output too well..
> Print debug conf output per row

- README.md
- libretro/libretro-core.c
- libretro/libretro-glue.c
- libretro/libretro-glue.h
- retrodep/sysconfig.h
- sources/src/filesys.c
- sources/src/fsusage.c
- sources/src/hardfile.c
- sources/src/hardfile_unix.c
- Large HDFs (>2GB)
- Hardfile backports/updates
- Automatic RDB detection on launch
- Increase directory filesystem fake usage/total/avail
> Hard drive updates

- libretro/libretro-core.c
- libretro/libretro-dc.c
This adds basic support for loading RP9 files, which are distributed by Cloanto in their Amiga Forever package and are just renamed zip files with an adf/hdf file located inside (plus metadata used by Amiga Forever).
> Add basic support for loading RP9 files

- libretro/libretro-core.c
- sources/src/cfgfile.c
`savefiles_in_content_dir` in combination with one-letter directories causes memory corruption in Linux, thus:
- Remove ending slash from `saves` path
- Also disregard one-letter subdirectories, so that WHDLoad data is saved in one place instead
Closes #437
> Save path fix + hack

- README.md
- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-glue.c
- Core option for forcing Kickstart, so that AROS can be used even with proper Kickstarts in place
- A500 512KB preset uses v1.2 KS
- Added 2 A2000 presets: "v1.2, 512KB+512KB" & "v3.1, 1MB"
- Model & Kickstart options get the final say even with custom uae confs
- Kickstarts no longer have to be renamed to the WHDLoad required format
- Amiga Forever + TOSEC are recognized, and WHDLoad will still get the proper format in both modes
> Kickstart improvements

- libretro/libretro-core.c
This PR just fixes 3 string-manipulation-related heap buffer overflows in `retro_create_config()`, affecting non-Windows platforms.
> Fix heap buffer overflows in retro_create_config()

- libretro/libretro-core.c
- libretro/libretro-dc.c
- libretro/libretro-glue.c
- libretro/libretro-graph.c
- libretro/libretro-mapper.c
- libretro/libretro-mapper.h
Video related:
- "Locked PAL/NTSC" option which forces rate to 50/59.94 regardless of interlace state so that audio buffer stays in line, making interlace toggling seamless. It maybe should be the new default, but no reason to rush yet.
- Geometry adjustments
Other:
- Added joystick directions to core option RetroPad mapper
- Removed possibility to add the same disk to DC list
- Adjusted core option sublabels
> Third "Allow Hz" mode + misc

- libretro/libretro-core.c
- retrodep/sounddep/sound.h
It increases the chance of audio dropouts. Also, it's better to submit
audio to the fronend after video, as the audio upload can block for a
long time and unnecessarily delay video frame presentation.
Fix this by accumulating all audio samples into a single output buffer
which is submitted at the end of each frame.
Reviewers
======
@sonninnos @jdgleaver
> Don't upload audio to frontend multiple times per frame

- sources/src/custom.c
Current default "Locked" option prevented non-standard switching in Dyna Blaster and BC Kid.
> Fix non-standard locked PAL/NTSC switch

- libretro/libretro-core.c
- libretro/libretro-glue.c
- Fixed fake NTSC modes going haywire after changing any core option
- Relocated video buffer reset to remove statusbar ghosting on standard & interlace toggle
> Auto region force + video buffer reset corrections

- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-glue.c
- libretro/libretro-mapper.c
- libretro/libretro-mapper.h
- libretro/libretro-vkbd.c
- libretro/libretro-vkbd.h
- sources/src/akiko.c
- sources/src/statusline.c
Zoom renamed everywhere to what the option actually does. Also included a method to automatically update the current options for the newly named keys.
> Rename Zoom to Crop

- Makefile
- `-lm` is necessary to sucessfully link puae & `-lpthread -ldl` where needed for glibc < 2.34 too
> Makefile: fix linking for armv

- Makefile
This fixes opening LHA files and addresses #541 and #542.
> Added required flag to support concurrency for iOS/tvOS

- Makefile
- Makefile.common
- deps/libz/gzguts.h
- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-dc.c
- libretro/libretro-dc.h
- libretro/libretro-glue.c
- libretro/libretro-glue.h
- retrodep/fsdb_host.c
- sources/src/disk.c
- Harnessed UAE internal save disk substitution feature as core option "Floppy Write Redirect", which is either on or off, and affecting all disks, not only IPF. Effectively allows writing to IPFs.
1. UAE deletes created save disks that are not written to
2. Resulting disks are gzipped and extracted silently
Closes #550
- WHDLoad info launch path fix
Closes #575
- Also gzipped the old manually created save disks
- Initialized the old save disk feature values to prevent a crash in certain situation (disk index moved manually to save disk index first, and then pressed save disk toggle hotkey)
- One more vertical position correction
- Fix for Speris Legacy startup interlace toggle issue when using Cycle-exact
> Floppy Write Redirect option

- libretro/libretro-core.c
VFS callbacks fail since it requires V2, which includes vfs_truncate. Otherwise it falls back to libretro-common code. Current VFS wrapping code in libretro-common needs V2 since vfs_truncate's callback is set.
https://github.com/libretro/libretro-common/blob/master/streams/file_stream.c#L65
Now VFS callbacks work properly in frontends that support them. Otherwise a hack of setting "cb->required_interface_version = 2" in frontend works. Only cores, according to specs, are meant to set the required version.
> Use proper VFS version.

- libretro/libretro-core.c
This PR fixes core variables for frontends that require the variables to be set inside retro_set_environment().
The documentation of `RETRO_ENVIRONMENT_SET_VARIABLES` states:
> This should be called the first time as early as possible (ideally in retro_set_environment).
>
> Afterward it may be called again for the core to communicate updated options to the frontend, but the number of core options must not change from the number in the initial call.
By calling `retro_set_core_options()` both inside retro_set_environment and when loading a game, we satisfy the libretro documentation.
This PR is fully analogous to https://github.com/libretro/vice-libretro/pull/488 (indeed, the diff is nearly identical).
Used to generate the Kodi game add-on for PUAE: …
> Fix core options not set in retro_set_environment()

- libretro/libretro-glue.c
Toggle CD32 pad type on and off properly when using mouse and when not. Fixes mouse drifting issue in Beneath a Steel Sky.
> Automatic CD32 pad switching mouse fix

- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-glue.c
- sources/src/include/uae.h
- sources/src/main.c
Eliminate the need for `NoWriteCache` by making sure WHDLoad is closed before closing core. This helps with a bunch of loading issues, and allows updating WHDLoad in the future, since the save issue does not exist with write cache.
Old behavior is kept as an option just in case, so nothing needs to be done to get the change. Please inform about any possible unsaved data!
> WHDLoad optional NoWriteCache

- sources/src/memory.c
Legacy non-`NATMEM_OFFSET` `mapped_free` isn't taking new features into account, and thus is trying to free non-allocated memory.
Closes #621
> 'mapped_free' update

- libretro/libretro-core.c
- libretro/libretro-core.h
- libretro/libretro-glue.c
- libretro/libretro-mapper.c
- libretro/libretro-vkbd.c
- sources/src/drawing.c
- sources/src/statusline.c
- Replace cropping and centering with video callback offset
Closes #640
- Improve game specific centering and resolution switch (Super Skidmarks) hacks for less false positives
- Allow using NTSC pixel aspect while in full height PAL without cutting the image
Also:
- Fix audio filter type not updating properly after restart
- Mute empty floppy drive by default
The old 2021 core will get these too once the dust settles and no major issues are discovered.
> Replace internal centering with video_cb offset

- libretro/libretro-mapper.c
The analog mouse currently has a slowest speed given by the fact that the process_analog_mouse function can return only a minimum value of 1. The code automatically turns the analog mouse into a digital mouse if the motion would be smaller than an integer value of 1. This is still pretty fast motion and makes it almost impossible to precisely position the pointer over a single pixel using the analog stick. It makes playing a game like Dreamweb with the analog stick extremely frustrating, even when holding down the slow mouse hotkey.
This following part in the existing code turns a very slow, analog, stick mouse movement (which would result in an increment of less than 1) into a faster, digital, movement:
```
if (!mouse_axis && abs(analog_axis) > analog_deadzone)
mouse_axis = (analog_axis …
```
> Increase analog stick mouse precision to sub-pixel

- README.md
- libretro/libretro-core.c
- libretro/libretro-mapper.c
- libretro/libretro-mapper.h
- libretro/libretro-vkbd.c
- Moved hardcoded WHDLoad QuitKey from `RETROK_KP_MINUS` to `RETROK_HASH`
- Allowed pressing `RETROK_HASH` with `RETROK_LCTRL + RETROK_BACKSLASH`
- Added specific VKBD + RetroPad mapper button
> WHDLoad QuitKey improvement
